import { createTypeSpecLibrary } from "@typespec/compiler";

export const $lib = createTypeSpecLibrary({
  name: "drizzle",
  diagnostics: {},
  // Defined state keys for storing metadata in decorator.
  state: {
    table: { description: "tableName" },
    id: { description: "id of row" },
    index: { description: "index this column" },
    map: { description: "map this property to column name" },
    uuid: { description: "value is a generated uuid" },
    default: { description: "default value for column" },
    unique: { description: "unique value per table" },
    sql: { description: "sql generated by db" },
    relation: { description: "relation to other model" },
    config: { description: "config for namespace" },
  },
});

export const {
  reportDiagnostic,
  createDiagnostic,
  stateKeys: StateKeys,
  createStateSymbol,
} = $lib;
