name: Publish Package to npmjs
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@octocat'
      - name: Setup Yarn    
        run: yarn set version 4.3.1 --yarn-path
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Run Yarn
        run: yarn 
      - name: Install Token Fix
        run: yarn fix
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build Skibididrizz    
        run: yarn workspace @skibididrizz/drizzle build       
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish to npm
        run: yarn npm login --always-auth && yarn workspace @skibididrizz/drizzle npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        